//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/proxy_enhanced/messages/control_messages/ACK_FlowBindingUpdate.msg.
//

#ifndef _ACK_FLOWBINDINGUPDATE_M_H_
#define _ACK_FLOWBINDINGUPDATE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/mcoa/proxy_enhanced/messages/control_messages/ACK_FlowBindingUpdate.msg</tt> by opp_msgc.
 * <pre>
 * packet ACK_FlowBindingUpdate {
 *    string HomeAddress;
 *    string NewCoAdress;
 *    string DestAddress;
 *    bool wasSendFromHA;
 * }
 * </pre>
 */
class ACK_FlowBindingUpdate : public ::cPacket
{
  protected:
    opp_string HomeAddress_var;
    opp_string NewCoAdress_var;
    opp_string DestAddress_var;
    bool wasSendFromHA_var;

  private:
    void copy(const ACK_FlowBindingUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ACK_FlowBindingUpdate&);

  public:
    ACK_FlowBindingUpdate(const char *name=NULL, int kind=0);
    ACK_FlowBindingUpdate(const ACK_FlowBindingUpdate& other);
    virtual ~ACK_FlowBindingUpdate();
    ACK_FlowBindingUpdate& operator=(const ACK_FlowBindingUpdate& other);
    virtual ACK_FlowBindingUpdate *dup() const {return new ACK_FlowBindingUpdate(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getHomeAddress() const;
    virtual void setHomeAddress(const char * HomeAddress);
    virtual const char * getNewCoAdress() const;
    virtual void setNewCoAdress(const char * NewCoAdress);
    virtual const char * getDestAddress() const;
    virtual void setDestAddress(const char * DestAddress);
    virtual bool getWasSendFromHA() const;
    virtual void setWasSendFromHA(bool wasSendFromHA);
};

inline void doPacking(cCommBuffer *b, ACK_FlowBindingUpdate& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ACK_FlowBindingUpdate& obj) {obj.parsimUnpack(b);}


#endif // _ACK_FLOWBINDINGUPDATE_M_H_
