//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/proxy_enhanced/messages/app_messages/RequestVideoStream.msg.
//

#ifndef _REQUESTVIDEOSTREAM_M_H_
#define _REQUESTVIDEOSTREAM_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/mcoa/proxy_enhanced/messages/app_messages/RequestVideoStream.msg</tt> by opp_msgc.
 * <pre>
 * packet RequestVideoStream {
 *   
 *   
 *   
 *   
 * }
 * </pre>
 */
class RequestVideoStream : public ::cPacket
{
  protected:

  private:
    void copy(const RequestVideoStream& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestVideoStream&);

  public:
    RequestVideoStream(const char *name=NULL, int kind=0);
    RequestVideoStream(const RequestVideoStream& other);
    virtual ~RequestVideoStream();
    RequestVideoStream& operator=(const RequestVideoStream& other);
    virtual RequestVideoStream *dup() const {return new RequestVideoStream(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, RequestVideoStream& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RequestVideoStream& obj) {obj.parsimUnpack(b);}


#endif // _REQUESTVIDEOSTREAM_M_H_
