//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/Video/MCoAVideoStreaming.msg.
//

#ifndef _MCOAVIDEOSTREAMING_M_H_
#define _MCOAVIDEOSTREAMING_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>applications/mcoa/Video/MCoAVideoStreaming.msg</tt> by opp_msgc.
 * <pre>
 * packet MCoAVideoStreaming {
 *     int curSeq; 
 *     double curTime; 
 * }
 * </pre>
 */
class MCoAVideoStreaming : public ::cPacket
{
  protected:
    int curSeq_var;
    double curTime_var;

  private:
    void copy(const MCoAVideoStreaming& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MCoAVideoStreaming&);

  public:
    MCoAVideoStreaming(const char *name=NULL, int kind=0);
    MCoAVideoStreaming(const MCoAVideoStreaming& other);
    virtual ~MCoAVideoStreaming();
    MCoAVideoStreaming& operator=(const MCoAVideoStreaming& other);
    virtual MCoAVideoStreaming *dup() const {return new MCoAVideoStreaming(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getCurSeq() const;
    virtual void setCurSeq(int curSeq);
    virtual double getCurTime() const;
    virtual void setCurTime(double curTime);
};

inline void doPacking(cCommBuffer *b, MCoAVideoStreaming& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MCoAVideoStreaming& obj) {obj.parsimUnpack(b);}


#endif // _MCOAVIDEOSTREAMING_M_H_
